In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [7]:
Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list which can hold elements of any data type, including integers, floats, strings, and so on.

On the other hand, the variable array_list is a numpy array which can only hold elements of the same data type. In this case, since all the elements of list_ are strings, the elements of array_list will also be converted to strings.

In [8]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [11]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
for i in list_:
    print("Data type of ", i, "in list_:", type(i))
for j in array_list:
    print("Data type of ", j, "in array_list:", type(j))


Data type of  1 in list_: <class 'str'>
Data type of  2 in list_: <class 'str'>
Data type of  3 in list_: <class 'str'>
Data type of  4 in list_: <class 'str'>
Data type of  5 in list_: <class 'str'>
Data type of  1 in array_list: <class 'numpy.str_'>
Data type of  2 in array_list: <class 'numpy.str_'>
Data type of  3 in array_list: <class 'numpy.str_'>
Data type of  4 in array_list: <class 'numpy.str_'>
Data type of  5 in array_list: <class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and array_list.

In [ ]:
Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list if you change the dtype parameter to int while creating array_list.

The int data type will convert each element in list_ from a string to an integer, and the resulting array_list will contain elements of the int data type.


In [12]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)
for i in list_:
    print("Data type of ", i, "in list_:", type(i))
for j in array_list:
    print("Data type of ", j, "in array_list:", type(j))


Data type of  1 in list_: <class 'str'>
Data type of  2 in list_: <class 'str'>
Data type of  3 in list_: <class 'str'>
Data type of  4 in list_: <class 'str'>
Data type of  5 in list_: <class 'str'>
Data type of  1 in array_list: <class 'numpy.int64'>
Data type of  2 in array_list: <class 'numpy.int64'>
Data type of  3 in array_list: <class 'numpy.int64'>
Data type of  4 in array_list: <class 'numpy.int64'>
Data type of  5 in array_list: <class 'numpy.int64'>


In [ ]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [15]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print("shape of num_array:",num_array.shape)
print("size of num_array:",num_array.size)

shape of num_array: (2, 3)
size of num_array: 6


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [17]:
import numpy as np
zeros_matrix = np.zeros(shape=(3, 3))
print(zeros_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [18]:
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
